// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test6_FinalTest.Data;

#nullable disable

namespace Test6FinalTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230103104055_Create_Table_NTS0999")]
    partial class CreateTableNTS0999
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("Test6_FinalTest.Models.CompanyNTS999", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CompanyId");

                    b.ToTable("CompanyNTS999");
                });

            modelBuilder.Entity("Test6_FinalTest.Models.NTS0999", b =>
                {
                    b.Property<string>("NTSId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NTSGender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NTSName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("NTSId");

                    b.ToTable("NTS0999");
                });
#pragma warning restore 612, 618
        }
    }
}
